echo "<button class='btn btn-sm btn-link' id='showdetails' data-toggle='popover' title='Details' data-html='true' data-content=' ";
	echo '<div>First Name: ';
	echo $value->customerFName;
	echo '</div><div>Last Name: ';
	echo $value->customerLName;
	echo '</div>';
	echo form_open('MGTracker/assignType');
	echo '<div>Email: ';
	echo '<input type="text" class="form-control form-control-plaintext form-control-sm" name = "email" value="'; 
	echo $value->CustomerEmail;
	echo '" "readonly">';
	echo '</div><div>Phone Number';
	echo $value->customerPhone;
	echo '</div><div>Role';
	echo '<input type="text" class="form-control form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '"></div>';
	echo "<div>";
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo "</div>";
	echo form_close();
	echo "'>";
	echo $count;
	echo '</button>';