<?php
echo '<nav class="navbar navbar-expand-sm navbar-light bg-light">';
echo '<a class="navbar-brand" href="#"></a>';
echo '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>';
echo '<div id="navbar" class="collapse navbar-collapse role="navigation">';
echo '<ul class="navbar-nav mr-auto">';
echo '<li class="nav-item">';
echo '<a href="FarmMaterials" class="nav-link">Farm Materials</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a href="Crops" class="nav-link">Crops</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a href="Nutrients" class="nav-link">Nutrients</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a href="Retail" class="nav-link">Retail</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a id="showProfile" class="nav-link" data-toggle="modal" data-target="#profileView">Profile</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a href="./MGTracker/logout" class="nav-link">Log Out</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
//welcome message
echo '<div class="container">';
echo '<div id ="top" class="row"></div>';
echo '<div id="welcome" class="row">';
echo '<h4 class="col">';
$company = $this->session->userdata('company');
echo $company;
echo ' Dashboard</h4>';
echo '<p class="col"></p>';
echo '<p class="col">User: ';
$username = $this->session->userdata('username');
echo $username;
echo '</p>';
echo '</div>';
//reports - harvest 
echo '<div id="reports">';
echo '<h4>Reports</h4>';
//buttons
echo '<button type="button" id="showHarvest" class="btn btn-primary" data-toggle="collapse" href="#harvestInventory" role="button" aria-expanded="false" aria-controls="harvestInventory" style="margin-right:2%; margin-bottom:2%;">LifeTime Harvest</button>';
echo '<button type="button" id="showAvgHarvest" class="btn btn-primary" data-toggle="collapse" href="#avgHarvestInventory" role="button" aria-expanded="false" aria-controls="avgHarvestInventory" style="margin-right:2%; margin-bottom:2%;">Average LifeTime Harvest</button>';
echo '<button type="button" id="showWinterHarvest" class="btn btn-primary" data-toggle="collapse" href="#winterHarvestInventory" role="button" aria-expanded="false" aria-controls="winterHarvestInventory" style="margin-right:2%; margin-bottom:2%;">Winter</button>';
echo '<button type="button" id="showSpringHarvest" class="btn btn-primary" data-toggle="collapse" href="#springHarvestInventory" role="button" aria-expanded="false" aria-controls="springHarvestInventory" style="margin-right:2%; margin-bottom:2%;">Spring</button>';
echo '<button type="button" id="showSummerHarvest" class="btn btn-primary" data-toggle="collapse" href="#summerHarvestInventory" role="button" aria-expanded="false" aria-controls="summerHarvestInventory" style="margin-right:2%; margin-bottom:2%;">Summer</button>';
echo '<button type="button" id="showFallHarvest" class="btn btn-primary" data-toggle="collapse" href="#fallHarvestInventory" role="button" aria-expanded="false" aria-controls="fallHarvestInventory" style="margin-right:2%; margin-bottom:2%;">Fall</button>';
//buttons
echo '<div id="harvestInventory" class="collapse table-responsive">';
echo '<h4>Lifetime Harvest</h4>';
echo '<table class="table table-sm table-striped">';
//lifetime seed harvest
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">Crop</th>';
	echo '<th scope="col">Seed Name</th>';
	echo '<th scope="col">Seed Manufacturer</th>';
	echo '<th scope="col">Start Date</th>';
	echo '<th scope="col">Harvest Date</th>';
	echo '<th scope="col">Seed Used</th>';
	echo '<th scope="col">Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
foreach ($harvestInventory as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Crop Number: ';
	echo $value->flatNumber;
	echo '</div><div>Seed Name: ';
	echo $value->seedName;
	echo '</div><div>Seed Manufacturer: ';
	echo $value->seedManufacturer;
	echo '</div><div>Date Start: ';
	echo $value->dateStart;
	echo '</div><div>Germination Date: ';
	echo $value->dateLight;
	echo '</div><div>Harvest Date: ';
	echo $value->dateEnd;
	echo '</div><div>Seed Used: ';
	echo round($value->seedUsed, 2);
	echo 'g</div><div>Yield: ';
	echo round($value->yieldWeight);
	echo 'g</div><div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div><div>Yield Value: ';
	echo round($yieldValue = $value->yieldWeight/$value->seedUsed, 2);
	echo '</div><div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div><div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->seedName;
	echo '</td>';
	echo '<td>';
	echo $value->seedManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->dateStart;
	echo '</td>';
	echo '<td>';
	echo $value->dateEnd;
	echo '</td>';
	echo '<td>';
	echo round($value->seedUsed, 2);
	echo 'g</td>';
	echo '<td>';
	echo round($value->yieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showGermdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Flat Number: ';
	echo $value->flatNumber;
	echo '</div>';
	echo '<div>Germ Date: ';
	echo $value->dateLight;
	echo '</div>';
	echo '<div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div>';
	echo '<div>Yield Value: ';
	echo round($yieldValue = $value->yieldWeight/$value->seedUsed, 2);
	echo '</div>';
	echo '<div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '<div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}
//lifetime plant harvest
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">Crop</th>';
	echo '<th scope="col">Plant Name</th>';
	echo '<th scope="col">Plant Manufacturer</th>';
	echo '<th scope="col">Start Date</th>';
	echo '<th scope="col">Harvest Date</th>';
	echo '<th scope="col">Plants Used</th>';
	echo '<th scope="col">Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
foreach ($harvestPlantInventory as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Crop Number: ';
	echo $value->plantNumber;
	echo '</div><div>Plant Name: ';
	echo $value->plantName;
	echo '</div><div>Plant Manufacturer: ';
	echo $value->plantManufacturer;
	echo '</div><div>Date Start: ';
	echo $value->dateStart;
	echo '</div><div>Harvest Date: ';
	echo $value->dateEnd;
	echo '</div><div>Plants Used: ';
	echo $value->plantAmount;
	echo '</div><div>Yield: ';
	echo round($value->yieldWeight, 2);
	echo 'g</div><div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div><div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->plantName;
	echo '</td>';
	echo '<td>';
	echo $value->plantManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->dateStart;
	echo '</td>';
	echo '<td>';
	echo $value->dateEnd;
	echo '</td>';
	echo '<td>';
	echo $value->plantAmount;
	echo '</td>';
	echo '<td>';
	echo round($value->yieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showGermdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Plant Number: ';
	echo $value->plantNumber;
	echo '</div>';
	echo '<div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '<div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}
	echo '</tbody>';
echo '</table>';
echo '</div>';//close lifetime harvest
//avg harvest
echo '<div id="avgHarvestInventory" class="collapse table-responsive">';
echo '<h4>Average Lifetime Harvest</h4>';
echo '<table class="table table-sm table-striped">';
//average seed harvest
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">#</th>';
	echo '<th scope="col">Seed Name</th>';
	echo '<th scope="col">Seed Manufacturer</th>';
	echo '<th scope="col">Avg Seed Used</th>';
	echo '<th scope="col">Medium Name</th>';
	echo '<th scope="col">Medium Used</th>';
	echo '<th scope="col">Avg Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
foreach ($avgHarvestInventory as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
//button link to show full details
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Seed Name: ';
	echo $value->seedName;
	echo '</div><div>Seed Manufacturer: ';
	echo $value->seedManufacturer;
	echo '</div><div>Avg Seed Used: ';
	echo round($value->avgSeedUsed, 2);
	echo 'g</div><div>Medium Name: ';
	echo $value->mediumName;
	echo '</div><div>Medium Manufacturer: ';
	echo $value->mediumManufacturer;
	echo '</div><div>Medium Used: ';
	echo round($value->totalMediumUsed);
	echo '</div><div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div><div>Avg Yield: ';
	echo round($value->avgYieldWeight);
	echo 'g</div><div>Avg Yield Value: ';
	echo round($yieldValue = $value->avgYieldWeight/$value->avgSeedUsed, 2);
	echo '</div><div>Avg Crop Rating: ';
	echo round($value->avgCropRating, 2);
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
//end button
	echo '</th>';
	echo '<td>';
	echo $value->seedName;
	echo '</td>';
	echo '<td>';
	echo $value->seedManufacturer;
	echo '</td>';
	echo '<td>';
	echo round($value->avgSeedUsed, 2);
	echo '</td>';
	echo '<td>';
	echo $value->mediumName;
	echo '</td>';
	echo '<td>';
	echo round($value->totalMediumUsed);
	echo '</td>';
	echo '<td>';
	echo round($value->avgYieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showAvgHarvestDetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Avg Yield Value: ';
	echo round($yieldValue = $value->avgYieldWeight/$value->avgSeedUsed, 2);
	echo '</div>';
	echo '<div>Medium Manufacturer: ';
	echo $value->mediumManufacturer;
	echo '</div>';
	echo '<div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div>';
	echo '<div>Average Crop Rating: ';
	echo round($value->avgCropRating, 2);
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}
//average plant harvest
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">#</th>';
	echo '<th scope="col">Plant Name</th>';
	echo '<th scope="col">Plant Manufacturer</th>';
	echo '<th scope="col">Plants Used</th>';
	echo '<th scope="col">Avg Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
foreach ($avgPlantHarvestInventory as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Plant Name: ';
	echo $value->plantName;
	echo '</div><div>Plant Manufacturer: ';
	echo $value->plantManufacturer;
	echo '</div><div>Avg Plants Used: ';
	echo round($value->avgPlantAmount);
	echo '</div><div>Avg Yield: ';
	echo round($value->avgYieldWeight, 2);
	echo 'g</div><div>Avg Crop Rating: ';
	echo round($value->avgCropRating, 2);
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->plantName;
	echo '</td>';
	echo '<td>';
	echo $value->plantManufacturer;
	echo '</td>';
	echo '<td>';
	echo round($value->avgPlantAmount);
	echo '<td>';
	echo round($value->avgYieldWeight, 2);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showAvgHarvestDetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Average Crop Rating: ';
	echo round($value->avgCropRating, 2);
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}
	echo '</tbody>';
echo '</table>';
echo '</div>';//close average plant harvest
//winter harvest
echo '<div id="winterHarvestInventory" class="collapse table-responsive">';
echo '<h4>Winter Harvest</h4>';
echo '<table class="table table-sm table-striped">';
//winter seed harvest
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">#</th>';
	echo '<th scope="col">Seed Name</th>';
	echo '<th scope="col">Seed Manufacturer</th>';
	echo '<th scope="col">Start Date</th>';
	echo '<th scope="col">Harvest Date</th>';
	echo '<th scope="col">Seed Used</th>';
	echo '<th scope="col">Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
foreach ($harvestInventory as $value) {
	$harvestDate = $value->dateEnd;
	if($harvestDate >= '2018-12-01' AND $harvestDate <= '2019-02-28'){
		$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
		echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Crop Number: ';
	echo $value->flatNumber;
	echo '</div><div>Seed Name: ';
	echo $value->seedName;
	echo '</div><div>Seed Manufacturer: ';
	echo $value->seedManufacturer;
	echo '</div><div>Date Start: ';
	echo $value->dateStart;
	echo '</div><div>Germination Date: ';
	echo $value->dateLight;
	echo '</div><div>Harvest Date: ';
	echo $value->dateEnd;
	echo '</div><div>Seed Used: ';
	echo round($value->seedUsed, 2);
	echo 'g</div><div>Yield: ';
	echo round($value->yieldWeight);
	echo 'g</div><div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div><div>Yield Value: ';
	echo round($yieldValue = $value->yieldWeight/$value->seedUsed, 2);
	echo '</div><div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div><div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->seedName;
	echo '</td>';
	echo '<td>';
	echo $value->seedManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->dateStart;
	echo '</td>';
	echo '<td>';
	echo $harvestDate;
	echo '</td>';
	echo '<td>';
	echo round($value->seedUsed, 2);
	echo 'g</td>';
	echo '<td>';
	echo round($value->yieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showGermdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Flat Number: ';
	echo $value->flatNumber;
	echo '</div>';
	echo '<div>Germ Date: ';
	echo $value->dateLight;
	echo '</div>';
	echo '<div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div>';
	echo '<div>Yield Value: ';
	echo round($yieldValue = $value->yieldWeight/$value->seedUsed, 2);
	echo '</div>';
	echo '<div> Crop Rating: ';
	echo $value->cropRating;
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '<div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}}
//winter plant harvest
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">#</th>';
	echo '<th scope="col">Plant Name</th>';
	echo '<th scope="col">Plant Manufacturer</th>';
	echo '<th scope="col">Start Date</th>';
	echo '<th scope="col">Harvest Date</th>';
	echo '<th scope="col">Plants Used</th>';
	echo '<th scope="col">Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
foreach ($harvestPlantInventory as $value) {
	$harvestDate = $value->dateEnd;
	if($harvestDate >= '2018-12-01' AND $harvestDate <= '2019-02-28'){
		$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Crop Number: ';
	echo $value->plantNumber;
	echo '</div><div>Plant Name: ';
	echo $value->plantName;
	echo '</div><div>Plant Manufacturer: ';
	echo $value->plantManufacturer;
	echo '</div><div>Date Start: ';
	echo $value->dateStart;
	echo '</div><div>Harvest Date: ';
	echo $value->dateEnd;
	echo '</div><div>Plants Used: ';
	echo $value->plantAmount;
	echo '</div><div>Yield: ';
	echo round($value->yieldWeight, 2);
	echo 'g</div><div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div><div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->plantName;
	echo '</td>';
	echo '<td>';
	echo $value->plantManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->dateStart;
	echo '</td>';
	echo '<td>';
	echo $value->dateEnd;
	echo '</td>';
	echo '<td>';
	echo $value->plantAmount;
	echo '</td>';
	echo '<td>';
	echo round($value->yieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showGermdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Plant Number: ';
	echo $value->plantNumber;
	echo '</div>';
	echo '<div> Crop Rating: ';
	echo $value->cropRating;
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '<div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}}
	echo '</tbody>';
echo '</table>';
echo '</div>';//close winter harvest
//Spring Harvest
echo '<div id="springHarvestInventory" class="collapse table-responsive">';
echo '<h4>Spring Harvest</h4>';
echo '<table class="table table-sm table-striped">';
//spring seed harvest
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">#</th>';
	echo '<th scope="col">Seed Name</th>';
	echo '<th scope="col">Seed Manufacturer</th>';
	echo '<th scope="col">Start Date</th>';
	echo '<th scope="col">Harvest Date</th>';
	echo '<th scope="col">Seed Used</th>';
	echo '<th scope="col">Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
foreach ($harvestInventory as $value) {
	$harvestDate = $value->dateEnd;
	if($harvestDate >= '2019-03-01' AND $harvestDate <= '2019-05-31'){
		$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
		echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Crop Number: ';
	echo $value->flatNumber;
	echo '</div><div>Seed Name: ';
	echo $value->seedName;
	echo '</div><div>Seed Manufacturer: ';
	echo $value->seedManufacturer;
	echo '</div><div>Date Start: ';
	echo $value->dateStart;
	echo '</div><div>Germination Date: ';
	echo $value->dateLight;
	echo '</div><div>Harvest Date: ';
	echo $value->dateEnd;
	echo '</div><div>Seed Used: ';
	echo round($value->seedUsed, 2);
	echo 'g</div><div>Yield: ';
	echo round($value->yieldWeight);
	echo 'g</div><div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div><div>Yield Value: ';
	echo round($yieldValue = $value->yieldWeight/$value->seedUsed, 2);
	echo '</div><div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div><div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->seedName;
	echo '</td>';
	echo '<td>';
	echo $value->seedManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->dateStart;
	echo '</td>';
	echo '<td>';
	echo $harvestDate;
	echo '</td>';
	echo '<td>';
	echo round($value->seedUsed, 2);
	echo 'g</td>';
	echo '<td>';
	echo round($value->yieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showGermdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Flat Number: ';
	echo $value->flatNumber;
	echo '</div>';
	echo '<div>Germ Date: ';
	echo $value->dateLight;
	echo '</div>';
	echo '<div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div>';
	echo '<div>Yield Value: ';
	echo round($yieldValue = $value->yieldWeight/$value->seedUsed, 2);
	echo '</div>';
	echo '<div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '<div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}}
//spring plant harvest
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">#</th>';
	echo '<th scope="col">Plant Name</th>';
	echo '<th scope="col">Plant Manufacturer</th>';
	echo '<th scope="col">Start Date</th>';
	echo '<th scope="col">Harvest Date</th>';
	echo '<th scope="col">Plants Used</th>';
	echo '<th scope="col">Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
$count = 0;
foreach ($harvestPlantInventory as $value) {
	$harvestDate = $value->dateEnd;
	if($harvestDate >= '2019-03-01' AND $harvestDate <= '2019-05-31'){
		$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Crop Number: ';
	echo $value->plantNumber;
	echo '</div><div>Plant Name: ';
	echo $value->plantName;
	echo '</div><div>Plant Manufacturer: ';
	echo $value->plantManufacturer;
	echo '</div><div>Date Start: ';
	echo $value->dateStart;
	echo '</div><div>Harvest Date: ';
	echo $value->dateEnd;
	echo '</div><div>Plants Used: ';
	echo $value->plantAmount;
	echo '</div><div>Yield: ';
	echo round($value->yieldWeight, 2);
	echo 'g</div><div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div><div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->plantName;
	echo '</td>';
	echo '<td>';
	echo $value->plantManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->dateStart;
	echo '</td>';
	echo '<td>';
	echo $value->dateEnd;
	echo '</td>';
	echo '<td>';
	echo $value->plantAmount;
	echo '</td>';
	echo '<td>';
	echo round($value->yieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showGermdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Plant Number: ';
	echo $value->plantNumber;
	echo '</div>';
	echo '<div> Crop Rating: ';
	echo $value->cropRating;
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '<div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}}
	echo '</tbody>';
echo '</table>';
echo '</div>';//close spring harvest
//summer harvest
echo '<div id="summerHarvestInventory" class="collapse table-responsive">';
echo '<h4>Summer Harvest</h4>';
echo '<table class="table table-sm table-striped">';
//summer seed harvest
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">#</th>';
	echo '<th scope="col">Seed Name</th>';
	echo '<th scope="col">Seed Manufacturer</th>';
	echo '<th scope="col">Start Date</th>';
	echo '<th scope="col">Harvest Date</th>';
	echo '<th scope="col">Seed Used</th>';
	echo '<th scope="col">Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
foreach ($harvestInventory as $value) {
	$harvestDate = $value->dateEnd;
	if($harvestDate >= '2019-06-01' AND $harvestDate <= '2019-08-31'){
		$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
		echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Crop Number: ';
	echo $value->flatNumber;
	echo '</div><div>Seed Name: ';
	echo $value->seedName;
	echo '</div><div>Seed Manufacturer: ';
	echo $value->seedManufacturer;
	echo '</div><div>Date Start: ';
	echo $value->dateStart;
	echo '</div><div>Germination Date: ';
	echo $value->dateLight;
	echo '</div><div>Harvest Date: ';
	echo $value->dateEnd;
	echo '</div><div>Seed Used: ';
	echo round($value->seedUsed, 2);
	echo 'g</div><div>Yield: ';
	echo round($value->yieldWeight);
	echo 'g</div><div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div><div>Yield Value: ';
	echo round($yieldValue = $value->yieldWeight/$value->seedUsed, 2);
	echo '</div><div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div><div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->seedName;
	echo '</td>';
	echo '<td>';
	echo $value->seedManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->dateStart;
	echo '</td>';
	echo '<td>';
	echo $harvestDate;
	echo '</td>';
	echo '<td>';
	echo round($value->seedUsed, 2);
	echo 'g</td>';
	echo '<td>';
	echo round($value->yieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showGermdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Flat Number: ';
	echo $value->flatNumber;
	echo '</div>';
	echo '<div>Germ Date: ';
	echo $value->dateLight;
	echo '</div>';
	echo '<div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div>';
	echo '<div>Yield Value: ';
	echo round($yieldValue = $value->yieldWeight/$value->seedUsed, 2);
	echo '</div>';
	echo '<div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '<div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}}
//summer plant harvest
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">#</th>';
	echo '<th scope="col">Plant Name</th>';
	echo '<th scope="col">Plant Manufacturer</th>';
	echo '<th scope="col">Start Date</th>';
	echo '<th scope="col">Harvest Date</th>';
	echo '<th scope="col">Plants Used</th>';
	echo '<th scope="col">Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
foreach ($harvestPlantInventory as $value) {
	$harvestDate = $value->dateEnd;
	if($harvestDate >= '2019-06-01' AND $harvestDate <= '2019-08-31'){
		$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Crop Number: ';
	echo $value->plantNumber;
	echo '</div><div>Plant Name: ';
	echo $value->plantName;
	echo '</div><div>Plant Manufacturer: ';
	echo $value->plantManufacturer;
	echo '</div><div>Date Start: ';
	echo $value->dateStart;
	echo '</div><div>Harvest Date: ';
	echo $value->dateEnd;
	echo '</div><div>Plants Used: ';
	echo $value->plantAmount;
	echo '</div><div>Yield: ';
	echo round($value->yieldWeight, 2);
	echo 'g</div><div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div><div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->plantName;
	echo '</td>';
	echo '<td>';
	echo $value->plantManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->dateStart;
	echo '</td>';
	echo '<td>';
	echo $value->dateEnd;
	echo '</td>';
	echo '<td>';
	echo $value->plantAmount;
	echo '</td>';
	echo '<td>';
	echo round($value->yieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showGermdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Plant Number: ';
	echo $value->plantNumber;
	echo '</div>';
	echo '<div> Crop Rating: ';
	echo $value->cropRating;
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '<div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}}
	echo '</tbody>';
echo '</table>';
echo '</div>';//close spring harvest
//fall harvest
echo '<div id="fallHarvestInventory" class="collapse table-responsive">';
echo '<h4>Fall Harvest</h4>';
echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">#</th>';
	echo '<th scope="col">Seed Name</th>';
	echo '<th scope="col">Seed Manufacturer</th>';
	echo '<th scope="col">Start Date</th>';
	echo '<th scope="col">Harvest Date</th>';
	echo '<th scope="col">Seed Used</th>';
	echo '<th scope="col">Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
foreach ($harvestInventory as $value) {
	$harvestDate = $value->dateEnd;
	if($harvestDate >= '2019-09-01' AND $harvestDate <= '2019-11-31'){
		$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
		echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Crop Number: ';
	echo $value->flatNumber;
	echo '</div><div>Seed Name: ';
	echo $value->seedName;
	echo '</div><div>Seed Manufacturer: ';
	echo $value->seedManufacturer;
	echo '</div><div>Date Start: ';
	echo $value->dateStart;
	echo '</div><div>Germination Date: ';
	echo $value->dateLight;
	echo '</div><div>Harvest Date: ';
	echo $value->dateEnd;
	echo '</div><div>Seed Used: ';
	echo round($value->seedUsed, 2);
	echo 'g</div><div>Yield: ';
	echo round($value->yieldWeight);
	echo 'g</div><div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div><div>Yield Value: ';
	echo round($yieldValue = $value->yieldWeight/$value->seedUsed, 2);
	echo '</div><div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div><div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->seedName;
	echo '</td>';
	echo '<td>';
	echo $value->seedManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->dateStart;
	echo '</td>';
	echo '<td>';
	echo $harvestDate;
	echo '</td>';
	echo '<td>';
	echo round($value->seedUsed, 2);
	echo 'g</td>';
	echo '<td>';
	echo round($value->yieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showGermdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Flat Number: ';
	echo $value->flatNumber;
	echo '</div>';
	echo '<div>Germ Date: ';
	echo $value->dateLight;
	echo '</div>';
	echo '<div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div>';
	echo '<div>Yield Value: ';
	echo round($yieldValue = $value->yieldWeight/$value->seedUsed, 2);
	echo '</div>';
	echo '<div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '<div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}}
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">#</th>';
	echo '<th scope="col">Plant Name</th>';
	echo '<th scope="col">Plant Manufacturer</th>';
	echo '<th scope="col">Start Date</th>';
	echo '<th scope="col">Harvest Date</th>';
	echo '<th scope="col">Plants Used</th>';
	echo '<th scope="col">Yield</th>';
	echo '<th scope="col">Details</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
foreach ($harvestPlantInventory as $value) {
	$harvestDate = $value->dateEnd;
	if($harvestDate >= '2019-09-01' AND $harvestDate <= '2019-11-31'){
		$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Crop Number: ';
	echo $value->plantNumber;
	echo '</div><div>Plant Name: ';
	echo $value->plantName;
	echo '</div><div>Plant Manufacturer: ';
	echo $value->plantManufacturer;
	echo '</div><div>Date Start: ';
	echo $value->dateStart;
	echo '</div><div>Harvest Date: ';
	echo $value->dateEnd;
	echo '</div><div>Plants Used: ';
	echo $value->plantAmount;
	echo '</div><div>Yield: ';
	echo round($value->yieldWeight, 2);
	echo 'g</div><div>Crop Rating: ';
	echo $value->cropRating;
	echo '</div><div>Test/Prod: ';
	echo $value->testing;
	echo '</div><div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->plantName;
	echo '</td>';
	echo '<td>';
	echo $value->plantManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->dateStart;
	echo '</td>';
	echo '<td>';
	echo $value->dateEnd;
	echo '</td>';
	echo '<td>';
	echo $value->plantAmount;
	echo '</td>';
	echo '<td>';
	echo round($value->yieldWeight);
	echo 'g</td>';
	echo '<td>';
	echo $value->cropRating;
	echo '</td>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showGermdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Additional Details" data-html="true" data-content="';
	echo '<div>Plant Number: ';
	echo $value->plantNumber;
	echo '</div>';
	echo '<div> Crop Rating: ';
	echo $value->cropRating;
	echo '</div>';
	echo '<div>Test/Prod: ';
	echo $value->testing;
	echo '</div>';
	echo '<div>Location: ';
	echo $value->location;
	echo '</div>';
	echo '">details</button>';
	echo '</td>';
	echo '</tr>';
}}
	echo '</tbody>';
echo '</table>';
echo '</div>';//close fall harvest
echo '</div>';//close reports
//farm material inventory
echo '<div id="farmMaterialInventory">';
echo '<div id="inventory_buttons">';
echo '<h4>Farm Material Inventory</h4>';
echo '<button type="button" id="showSeeds" class="btn btn-primary" data-toggle="collapse" href="#seedInventory" role="button" aria-expanded="false" aria-controls="seedInventory" style="margin-right:2%; margin-bottom:2%;">Seeds</button>';
echo '<button type="button" id="showPlants" class="btn btn-primary" data-toggle="collapse" href="#plantInventory" role="button" aria-expanded="false" aria-controls="plantInventory" style="margin-right:2%; margin-bottom:2%;">Plants</button>';
echo '<button type="button" id="showMedium" class="btn btn-primary" data-toggle="collapse" href="#mediumInventory" role="button" aria-expanded="false" aria-controls="mediumInventory" style="margin-right:2%; margin-bottom:2%;">Medium</button>';
echo '<button type="button" id="showNutrient" class="btn btn-primary" data-toggle="collapse" href="#nutrientInventory" role="button" aria-expanded="false" aria-controls="nutrientInventory" style="margin-right:2%; margin-bottom:2%;">Nutrients</button>';
echo '<button type="button" id="showEquipment" class="btn btn-primary" data-toggle="collapse" href="#equipmentInventory" role="button" aria-expanded="false" aria-controls="equipmentInventory" style="margin-right:2%; margin-bottom:2%;">Equipment</button>';
echo '</div>';//close inventory buttons
//seed inventory
echo '<div id="seedInventory" class="collapse table-responsive">';
echo '<h4>Seed Inventory</h4>';
echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">Seed Name</th>';
	echo '<th scope="col">Seed Manufacturer</th>';
	echo '<th scope="col">Seed Amount</th>';
	echo '<th scope="col">Seed Used</th>';
	echo '<th scope="col">Seed Remainder</th>';
	echo '<th scope="col">Average Seed Cost</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
//Used Seed
foreach ($seedPurchasedInventory as $value) {
		$seedNamePurchased = $value->seedName;
		$seedManufacturerPurchased = $value->seedManufacturer;
		$seedAmountPurchased = $value->seedInputTotal;
		$seedCost = $value->avgSeedPrice;
foreach ($seedUsedInventory as $value) {
		$seedNameUsed = $value->seedName;
		$seedManufacturerUsed = $value->seedManufacturer;
		$usedSeed = $value->seedUsedTotal;
	if($seedNamePurchased === $seedNameUsed AND $seedManufacturerPurchased === $seedManufacturerUsed){
		$seedRemainder =  $seedAmountPurchased - $usedSeed;
		echo '<tr>';
		echo '<td>';
		echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
		echo '<div>Seed Name: ';
		echo $seedNamePurchased;
		echo '</div><div>Seed Manufacturer: ';
		echo $seedManufacturerPurchased;
		echo '</div><div> Seed Amount: ';
		echo round($seedAmountPurchased, 2);
		echo 'g</div><div>Seed Used: ';
		echo round($usedSeed, 2);
		echo 'g</div><div>Seed Remainder: ';
		echo round($seedRemainder, 2);
		echo 'g</div><div>Average Seed Cost: $';
		echo round($seedCost, 5);
		echo ' per g</div>';
		echo '">';
		echo $seedNamePurchased;
		echo '</button>';
		echo '</td>';
		echo '<td>';
		echo $seedManufacturerPurchased;
		echo '</td>';
		echo '<td>';
		echo round($seedAmountPurchased, 2);
		echo 'g</td>';
		echo '<td>';
		echo round($usedSeed, 2);
		echo 'g</td>';
		echo '<td>';
		echo round($seedRemainder, 2);
		echo 'g</td>';
		echo '<td>$';
		echo round($seedCost, 5);
		echo ' per g</td>';
		echo '</tr>';
	}
}}
//Seeds Not Used
foreach ($seedUnusedInventory as $value) {
		echo '<tr>';
		echo '<td>';
		echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
		echo '<div>Seed Name: ';
		echo $value->seedName;
		echo '</div><div>Seed Manufacturer: ';
		echo $value->seedManufacturer;
		echo '</div><div> Seed Amount: ';
		echo round($value->seedInputTotal, 2);
		echo 'g</div><div>Seed Used: ';
		echo '0g</div><div>Seed Remainder: ';
		echo round($value->seedInputTotal, 2);
		echo 'g</div><div>Average Seed Cost: $';
		echo round($value->avgSeedPrice, 5);
		echo ' per g</div>';
		echo '">';
		echo $value->seedName;
		echo '</button>';
		echo '</td>';
		echo '<td>';
		echo $value->seedManufacturer;
		echo '</td>';
		echo '<td>';
		echo round($value->seedInputTotal, 2);
		echo 'g</td>';
		echo '<td>';
		echo '0g</td>';
		echo '<td>';
		echo round($value->seedInputTotal, 2);
		echo 'g</td>';
		echo '<td>$';
		echo round($value->avgSeedPrice, 5);
		echo ' per g</td>';
		echo '</tr>';
}
echo '</tbody>';
echo '</table>';
echo '</div>'; //close seed inventory
//plant inventory
echo '<div id="plantInventory" class="collapse table-responsive">';
echo '<h4>Plant Inventory</h4>';
echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">Plant Name</th>';
	echo '<th scope="col">Plant Manufacturer</th>';
	echo '<th scope="col">Plant Amount</th>';
	echo '<th scope="col">Plant Used</th>';
	echo '<th scope="col">Plant Remainder</th>';
	echo '<th scope="col">Average Plant Cost</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
//Used plant
foreach ($plantPurchasedInventory as $value) {
		$plantNamePurchased = $value->plantName;
		$plantManufacturerPurchased = $value->plantManufacturer;
		$plantAmountPurchased = $value->plantInputTotal;
		$plantCost = $value->avgPlantPrice;
foreach ($plantUsedInventory as $value) {
		$plantNameUsed = $value->plantName;
		$plantManufacturerUsed = $value->plantManufacturer;
		$usedplant = $value->plantUsedTotal;
	if($plantNamePurchased === $plantNameUsed AND $plantManufacturerPurchased === $plantManufacturerUsed){
		$plantRemainder =  $plantAmountPurchased - $usedplant;
		echo '<tr>';
		echo '<td>';
		echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
		echo '<div>Plant Name: ';
		echo $plantNamePurchased;
		echo '</div><div>Plant Manufacturer: ';
		echo $plantManufacturerPurchased;
		echo '</div><div>Plant Amount: ';
		echo $plantAmountPurchased;
		echo '</div><div>Plant Used: ';
		echo $usedplant;
		echo '</div><div>Plant Remainder: ';
		echo $plantRemainder;
		echo '</div><div>Average Plant Cost: $';
		echo round($plantCost, 5);
		echo '</div>';
		echo '">';
		echo $plantNamePurchased;
		echo '</button>';
		echo '</td>';
		echo '<td>';
		echo $plantManufacturerPurchased;
		echo '</td>';
		echo '<td>';
		echo $plantAmountPurchased;
		echo '</td>';
		echo '<td>';
		echo $usedplant;
		echo '</td>';
		echo '<td>';
		echo $plantRemainder;
		echo '</td>';
		echo '<td>$';
		echo round($plantCost, 5);
		echo '</td>';
		echo '</tr>';
	}
}}
//plants Not Used
foreach ($plantUnusedInventory as $value) {
		echo '<tr>';
		echo '<td>';
		echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
		echo '<div>Plant Name: ';
		echo $value->plantName;
		echo '</div><div>Plant Manufacturer: ';
		echo $value->plantManufacturer;
		echo '</div><div>Plant Amount: ';
		echo $value->plantInputTotal;
		echo '</div><div>Plant Used: ';
		echo '$0</div><div>Plant Remainder: ';
		echo $value->plantInputTotal;
		echo '</div><div>Average Plant Cost: $';
		echo round($value->avgPlantPrice, 5);
		echo '</div>';
		echo '">';
		echo $value->plantName;
		echo '</button>';		echo '</td>';
		echo '<td>';
		echo $value->plantManufacturer;
		echo '</td>';
		echo '<td>';
		echo $value->plantInputTotal;
		echo 'g</td>';
		echo '<td>';
		echo '0</td>';
		echo '<td>';
		echo $value->plantInputTotal;
		echo '</td>';
		echo '<td>$';
		echo round($value->avgPlantPrice, 5);
		echo '</td>';
		echo '</tr>';
}
echo '</tbody>';
echo '</table>';
echo '</div>';//close plant inventory
//medium inventory
echo '<div id="mediumInventory" class="collapse table-responsive">';
echo '<h4>Medium Inventory</h4>';
echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">Medium Name</th>';
	echo '<th scope="col">Medium Manufacturer</th>';
	echo '<th scope="col">Medium Material</th>';
	echo '<th scope="col">Material Purchased</th>';
	echo '<th scope="col">Material Used</th>';
	echo '<th scope="col">Material in Inventory</th>';
	echo '<th scope="col">Medium Average Cost</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
foreach ($mediumPurchasedInventory as $value){
	$mediumPurchasedName = $value->mediumName;
	$mediumPurchasedManufacturer = $value->mediumManufacturer;
	$mediumPurchasedMaterial = $value->mediumMaterial;
	$mediumPurchased = $value->mediumInputTotal;
	$mediumCost = $value->avgMediumCost;
foreach ($mediumUsedInventory as $value){
	$mediumUsedName = $value->mediumName;
	$mediumUsedManufacturer = $value->mediumManufacturer;
	$mediumUsedMaterial = $value->mediumMaterial;
	$mediumUsed = $value->mediumUsedTotal;
	if ($mediumPurchasedName === $mediumUsedName AND $mediumPurchasedManufacturer === $mediumUsedManufacturer AND $mediumPurchasedMaterial === $mediumUsedMaterial){
		$mediumRemainder = $mediumPurchased - $mediumUsed;
	echo '<tr>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Medium Name: ';
	echo $mediumPurchasedName;
	echo '</div><div>Medium Manufacturer: ';
	echo $mediumPurchasedManufacturer;
	echo '</div><div>Medium Material: ';
	echo $mediumPurchasedMaterial;
	echo '</div><div>Material Purchased: ';
	echo round($mediumPurchased, 2);
	echo '</div><div>Material Used: ';
	echo round($mediumUsed, 2);
	echo '</div><div>Material in Inventory: ';
	echo round($mediumRemainder, 2);
	echo '</div><div>Medium Average Cost: $';
	echo round($mediumCost, 5);
	echo '</div>';
	echo '">';
	echo $mediumPurchasedName;
	echo '</button>';
	echo '</td>';
	echo '<td>';
	echo $mediumPurchasedManufacturer;
	echo '</td>';
	echo '<td>';
	echo $mediumPurchasedMaterial;
	echo '</td>';
	echo '<td>';
	echo round($mediumPurchased, 2);
	echo '</td>';
	echo '<td>';
	echo round($mediumUsed, 2);
	echo '</td>';
	echo '<td>';
	echo round($mediumRemainder, 2);
	echo '</td>';
	echo '<td>$';
	echo round($mediumCost, 5);
	echo '</td>';
	echo '<td>';
	echo '</tr>';
	}
}}
//unused medium
foreach ($mediumUnusedInventory as $value) {
	echo '<tr>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Medium Name: ';
	echo $value->mediumName;
	echo '</div><div>Medium Manufacturer: ';
	echo $value->mediumManufacturer;
	echo '</div><div>Medium Material: ';
	echo $value->mediumMaterial;
	echo '</div><div>Material Purchased';
	echo round($value->mediumInputTotal, 2);
	echo '</div><div>Material Used: 0';
	echo '</div><div>Material in Inventory: ';
	echo round($value->mediumInputTotal, 2);
	echo '</div><div>Medium Average Cost: $';
	echo round($value->avgMediumCost, 5);
	echo '</div>';
	echo $value->mediumName;
	echo '</button>';
	echo '</td>';
	echo '<td>';
	echo $value->mediumManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->mediumMaterial;
	echo '</td>';
	echo '<td>';
	echo round($value->mediumInputTotal, 2);
	echo '</td>';
	echo '<td>';
	echo '0</td>';
	echo '<td>';
	echo round($value->mediumInputTotal, 2);
	echo '</td>';
	echo '<td>$';
	echo round($value->avgMediumCost, 5);
	echo '</td>';
	echo '</tr>';
}
	echo '</tbody>';
echo '</table>';
echo '</div>';//close medium inventory
//nutrient inventory
echo '<div id="nutrientInventory" class="collapse table-responsive">';
echo '<h4>Nutrient Inventory</h4>';
echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">Nutrient Name</th>';
	echo '<th scope="col">Nutrient Manufacturer</th>';
	echo '<th scope="col">Nutrient Purchased</th>';
	echo '<th scope="col">Nutrient Used</th>';
	echo '<th scope="col">Nutrient Inventory</th>';
	echo '<th scope="col">Nutrient Cost</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
foreach ($nutrientPurchasedInventory as $value){
	$nutrientPurchasedName = $value->nutrientName;
	$nutrientPurchasedManufacturer = $value->nutrientManufacturer;
	$nutrientPurchased = $value->nutrientInputTotal;
	$nutrientCost = $value->avgNutrientCost;
foreach ($nutrientUsedInventory as $value){
	$nutrientUsedName = $value->nutrientName;
	$nutrientUsedManufacturer = $value->nutrientManufacturer;
	$nutrientUsed = $value->nutrientUsedTotal;
	if ($nutrientPurchasedName === $nutrientUsedName AND $nutrientPurchasedManufacturer === $nutrientUsedManufacturer){
		$nutrientRemainder = $nutrientPurchased - $nutrientUsed;
	echo '<tr>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Nutrient Name';
	echo $nutrientPurchasedName;
	echo '</div><div>Nutrient Manufacturer: ';
	echo $nutrientPurchasedManufacturer;
	echo '</div><div>Nutrient Purchased: ';
	echo $nutrientPurchased;
	echo ' ml</div><div>Nutrient Used: ';
	echo $nutrientUsed;
	echo ' ml</div><div> Nutrient Inventory: ';
	echo $nutrientRemainder;
	echo ' ml</div><div>Nutrient Cost: $';
	echo round($nutrientCost, 5);
	echo ' per ml</div>';
	echo '">';
	echo $nutrientPurchasedName;
	echo '</button>';
	echo '</td>';
	echo '<td>';
	echo $nutrientPurchasedManufacturer;
	echo '</td>';
	echo '<td>';
	echo $nutrientPurchased;
	echo ' ml</td>';
	echo '<td>';
	echo $nutrientUsed;
	echo ' ml</td>';
	echo '<td>';
	echo $nutrientRemainder;
	echo ' ml</td>';
	echo '<td>$';
	echo round($nutrientCost, 5);
	echo ' per ml</td>';
	echo '<td>';
	echo '</tr>';
	}
}}
//unused nutrient
foreach ($nutrientUnusedInventory as $value) {
	echo '<tr>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Nutrient Name';
	echo $value->nutrientName;
	echo '</div><div>Nutrient Manufacturer: ';
	echo $value->nutrientManufacturer;
	echo '</div><div>Nutrient Purchased';
	echo $value->nutrientInputTotal;
	echo ' ml</div><div>Nutrient Used: ';
	echo '0 ml</div><div> Nutrient Inventory: ';
	echo $value->nutrientInputTotal;
	echo ' ml</div><div>Nutrient Cost: $';
	echo round($value->avgnutrientCost, 5);
	echo ' per ml</div>';
	echo '">';
	echo $value->nutrientName;
	echo '</button>';
	echo '</td>';
	echo '<td>';
	echo $value->nutrientManufacturer;
	echo '</td>';
	echo '<td>';
	echo $value->nutrientInputTotal;
	echo ' ml</td>';
	echo '<td>';
	echo '0</td>';
	echo '<td>';
	echo $value->nutrientInputTotal;
	echo ' ml</td>';
	echo '<td>$';
	echo round($value->avgnutrientCost, 5);
	echo ' per ml</td>';
	echo '</tr>';
}
	echo '</tbody>';
echo '</table>';
echo '</div>';//close medium inventory
//equipment inventory
echo '<div id="equipmentInventory" class="collapse table-responsive">';
echo '<h4>Equipment Inventory</h4>';
echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th scope="col">Equipment Name</th>';
	echo '<th scope="col">Equipment Type</th>';
	echo '<th scope="col">Equipment Vendor</th>';
	echo '<th scope="col">Equipment Manufacturer</th>';
	echo '<th scope="col">Equipment Price</th>';
	echo '<th scope="col">Equipment Amount</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
foreach ($equipmentPurchaseInventory as $row) {
	echo '<tr>';
	echo '<td>';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>Equipment Name: ';
	echo $row->equipmentName;
	echo '</div><div>Equipment Type: ';
	echo $row->equipmentType;
	echo '</div><div>Equipment Vendor: ';
	echo $row->equipmentVendor;
	echo '</div><div>Equipment Manufacturer: ';
	echo $row->equipmentManufacturer;
	echo '</div><div>Equipment Price: $';
	echo round($row->ePrice, 2);
	echo '</div><div>Equipment Amount: ';
	echo $row->eAmount;
	echo '</div>';
	echo '">';
	echo $row->equipmentName;
	echo '</button>';
	echo '</td>';
	echo '<td>';
	echo $row->equipmentType;
	echo '</td>';
	echo '<td>';
	echo $row->equipmentVendor;
	echo '</td>';
	echo '<td>';
	echo $row->equipmentManufacturer;
	echo '</td>';
	echo '<td>$';
	echo round($row->ePrice, 2);
	echo '</td>';
	echo '<td>';
	echo $row->eAmount;
	echo '</td>';
	echo '</tr>';
}
	echo '</tbody>';
echo '</table>';
echo '</div>';//close equipment inventory
echo '</div>';
?>
