<?php
$this->load->helper('form');
$usertype = $this->session->userdata('usertype');
if ($usertype === "admin"){
	echo "<h4>Contacts</h4>";
	//buttons
	echo '<button type="button" id="employeesContact" class="btn btn-primary" data-toggle="collapse" href="#employees" role="button" aria-expanded="false" aria-controls="employees" style="margin-right:2%; margin-bottom:2%;">Employees</button>';
	echo '<button type="button" id="customerContact" class="btn btn-primary" data-toggle="collapse" href="#customers" role="button" aria-expanded="false" aria-controls="customers" style="margin-right:2%; margin-bottom:2%;">Customers</button>';
	//employees
	echo '<div id="employees" class="collapse table-responsive">';
	echo '<h4>Employee Contacts</h4>';
	echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th>#</th>';
	echo '<th>First Name</th>';
	echo '<th>Last Name</th>';
	echo '<th>Email</th>';
	echo '<th>Phone Number</th>';
	echo '<th>Role<th>';
	echo '<th>Address</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
	foreach ($employee as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo "<button class='btn btn-sm btn-link' id='showdetails' data-toggle='popover' data-placement='left' title='Details' data-html='true' data-content=' ";
	echo '<div>First Name: ';
	echo $value->customerFName;
	echo '</div><div>Last Name: ';
	echo $value->customerLName;
	echo '</div>';
	echo form_open('MGTracker/assignType');
	echo '<input type="hidden" name="customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>Email: ';
	echo $value->CustomerEmail;
	echo '</div><div>Phone Number: ';
	echo $value->customerPhone;
	echo '</div><div>Address: ';
	echo $value->customerStreet." ".$value->customerTown.", ".$value->customerState." ".$value->customerZip ;
	echo '</div><div>Role';
	echo '<input type="text" class="form-control form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '"></div>';
	echo "<div>";
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo "</div>";
	echo form_close();
	echo "'>";
	echo $count;
	echo '</button>';
	echo '</th>';
	echo '<td>';
	echo $value->customerFName;
	echo '</td><td>';
	echo $value->customerLName;
	echo '</td>';
	echo form_open('MGTracker/assignType');
	echo '<input type="hidden" name="customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<td>'; 
	echo $value->CustomerEmail;
	echo '</td><td>';
	echo $value->customerPhone;
	echo '</td><td>';
	echo '<input type="text" class="form-control form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '">';
	echo '</td><td>';
	echo form_submit("submit", "update", "class='submit btn btn-primary btn-sm'");
	echo form_close();
	echo '</td>';
			//customer address and edit
	echo '<td>';
	echo "<button class='btn btn-sm btn-link' id='showAddress' data-toggle='popover' data-placement='left' title='Address' data-html='true' data-content=' ";
	echo '<div>';
	echo form_open('MGTracker/editAddress');
	echo '<input type="hidden" name = "customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>';
	echo form_label('Street', 'customerStreet');
	echo '<input type="text" class="form-control form-control-sm" name="customerStreet" value="';
	echo $value->customerStreet;
	echo '"></div>';
	echo '<div>';
	echo form_label('City', 'customerTown');
	echo '<input type="text" class="form-control form-control-sm" name="customerTown" value="';
	echo $value->customerTown;
	echo '"></div>';
	echo '<div>';
	echo form_label('State', 'customerState');
	echo '<input type="text" class="form-control form-control-sm" name="customerState" value="';
	echo $value->customerState;
	echo '"></div>';
	echo '<div>';
	echo form_label('Zip', 'customerZip');
	echo '<input type="text" class="form-control form-control-sm" name="customerZip" value="';
	echo $value->customerZip;
	echo '"></div>';
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo '</div>';
	echo form_close();
	echo "'>";
	echo 'Address</button>';
	echo '</td>';
	echo '</tr>';
	}
	echo '</tbody>';
	echo '</table>';
	echo '</div>';
//customers
	echo '<div id="customers" class="collapse table-responsive">';
	echo '<h4>Customers</h4>';
	echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th>#</th>';
	echo '<th>First Name</th>';
	echo '<th>Last Name</th>';
	echo '<th>Email</th>';
	echo '<th>Phone Number</th>';
	echo '<th>Role<th>';
	echo '<th>Address</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
	foreach ($customers as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo "<button class='btn btn-sm btn-link' id='showdetails' data-toggle='popover' data-placement='left' data-placement='left' title='Details' data-html='true' data-content=' ";
	echo '<div>First Name: ';
	echo $value->customerFName;
	echo '</div><div>Last Name: ';
	echo $value->customerLName;
	echo '</div>';
	echo form_open('MGTracker/assignType');
	echo '<input type="hidden" name="customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>Email: ';
	echo $value->CustomerEmail;
	echo '</div><div>Phone Number: ';
	echo $value->customerPhone;
	echo '</div><div>Address: ';
	echo $value->customerStreet." ".$value->customerTown.", ".$value->customerState." ".$value->customerZip ;
	echo '</div><div>Role';
	echo '<input type="text" class="form-control form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '"></div>';
	echo "<div>";
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo "</div>";
	echo form_close();
	echo "'>";
	echo $count;
	echo '</button>';
	echo '</th><td>';
	echo $value->customerFName;
	echo '</td><td>';
	echo $value->customerLName;
	echo '</td>';
	echo form_open('MGTracker/assignType');
	echo '<input type="hidden" name="customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<td>';	
	echo $value->CustomerEmail;
	echo '</td><td>';
	echo $value->customerPhone;
	echo '</td><td>';
	echo '<input type="text" class="form-control form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '">';
	echo '</td><td>';
	echo form_submit("submit", "update", "class='submit btn btn-primary btn-sm'");
	echo form_close();
	echo '</td>';
			//customer address and edit
	echo '<td>';
	echo "<button class='btn btn-sm btn-link' id='showAddress' data-toggle='popover' data-placement='left' title='Address' data-html='true' data-content=' ";
	echo '<div>';
	echo form_open('MGTracker/editAddress');
	echo '<input type="hidden" name = "customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>';
	echo form_label('Street', 'customerStreet');
	echo '<input type="text" class="form-control form-control-sm" name="customerStreet" value="';
	echo $value->customerStreet;
	echo '"></div>';
	echo '<div>';
	echo form_label('City', 'customerTown');
	echo '<input type="text" class="form-control form-control-sm" name="customerTown" value="';
	echo $value->customerTown;
	echo '"></div>';
	echo '<div>';
	echo form_label('State', 'customerState');
	echo '<input type="text" class="form-control form-control-sm" name="customerState" value="';
	echo $value->customerState;
	echo '"></div>';
	echo '<div>';
	echo form_label('Zip', 'customerZip');
	echo '<input type="text" class="form-control form-control-sm" name="customerZip" value="';
	echo $value->customerZip;
	echo '"></div>';
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo '</div>';
	echo form_close();
	echo "'>";
	echo 'Address</button>';
	echo '</td>';
	echo '</tr>';
	}
	echo '</tbody>';
	echo '</table>';
	echo '</div>';
}elseif($usertype === "superadmin"){
	echo "<h4>Contacts</h4>";
	//buttons
	echo '<button type="button" id="employeesContact" class="btn btn-primary" data-toggle="collapse" href="#employees" role="button" aria-expanded="false" aria-controls="employees" style="margin-right:2%; margin-bottom:2%;">Employees</button>';
	echo '<button type="button" id="customerContact" class="btn btn-primary" data-toggle="collapse" href="#customers" role="button" aria-expanded="false" aria-controls="customers" style="margin-right:2%; margin-bottom:2%;">Customers</button>';
	//employees
	echo '<div id="employees" class="collapse table-responsive">';
	echo '<h4>Employee Contacts</h4>';
	echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th>#</th>';
	echo '<th>First Name</th>';
	echo '<th>Last Name</th>';
	echo '<th>Email</th>';
	echo '<th>Phone Number</th>';
	echo '<th>Role<th>';
	echo '<th>Address</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
	foreach ($employee as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo "<button class='btn btn-sm btn-link' id='showdetails' data-toggle='popover' data-placement='left' title='Details' data-html='true' data-content=' ";
	echo '<div>First Name: ';
	echo $value->customerFName;
	echo '</div><div>Last Name: ';
	echo $value->customerLName;
	echo '</div>';
	echo form_open('MGTracker/assignType');
	echo '<input type="hidden" name="customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>Email: ';
	echo $value->CustomerEmail;
	echo '</div><div>Phone Number: ';
	echo $value->customerPhone;
	echo '</div><div>Address: ';
	echo $value->customerStreet." ".$value->customerTown.", ".$value->customerState." ".$value->customerZip ;
	echo '</div><div>Role';
	echo '<input type="text" class="form-control form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '"></div>';
	echo "<div>";
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo "</div>";
	echo form_close();
	echo "'>";
	echo $count;
	echo '</button>';
	echo '</th><td>';
	echo $value->customerFName;
	echo '</td><td>';
	echo $value->customerLName;
	echo '</td>';
	echo form_open('MGTracker/assignType');
	echo '<input type="hidden" name="customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<td>';
	echo $value->CustomerEmail;
	echo '</td><td>';
	echo $value->customerPhone;
	echo '</td><td>';
	echo '<input type="text" class="form-control form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '">';
	echo '</td><td>';
	echo form_submit("submit", "update", "class='submit btn btn-primary btn-sm'");
	echo form_close();
	echo '</td>';
			//customer address and edit
	echo '<td>';
	echo "<button class='btn btn-sm btn-link' id='showAddress' data-toggle='popover' data-placement='left' title='Address' data-html='true' data-content=' ";
	echo '<div>';
	echo form_open('MGTracker/editAddress');
	echo '<input type="hidden" name = "customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>';
	echo form_label('Street', 'customerStreet');
	echo '<input type="text" class="form-control form-control-sm" name="customerStreet" value="';
	echo $value->customerStreet;
	echo '"></div>';
	echo '<div>';
	echo form_label('City', 'customerTown');
	echo '<input type="text" class="form-control form-control-sm" name="customerTown" value="';
	echo $value->customerTown;
	echo '"></div>';
	echo '<div>';
	echo form_label('State', 'customerState');
	echo '<input type="text" class="form-control form-control-sm" name="customerState" value="';
	echo $value->customerState;
	echo '"></div>';
	echo '<div>';
	echo form_label('Zip', 'customerZip');
	echo '<input type="text" class="form-control form-control-sm" name="customerZip" value="';
	echo $value->customerZip;
	echo '"></div>';
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo '</div>';
	echo form_close();
	echo "'>";
	echo 'Address</button>';
	echo '</td>';
	echo '</tr>';
	}
	echo '</tbody>';
	echo '</table>';
	echo '</div>';
//customers
	echo '<div id="customers" class="collapse table-responsive">';
	echo '<h4>Customers</h4>';
	echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th>#</th>';
	echo '<th>First Name</th>';
	echo '<th>Last Name</th>';
	echo '<th>Email</th>';
	echo '<th>Phone Number</th>';
	echo '<th>Role<th>';
	echo '<th>Address</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
	foreach ($customers as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo "<button class='btn btn-sm btn-link' id='showdetails' data-toggle='popover' data-placement='left' title='Details' data-html='true' data-content=' ";
	echo '<div>First Name: ';
	echo $value->customerFName;
	echo '</div><div>Last Name: ';
	echo $value->customerLName;
	echo '</div>';
	echo form_open('MGTracker/assignType');
	echo '<input type="hidden" name="customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>Email: ';
	echo $value->CustomerEmail;
	echo '</div><div>Phone Number: ';
	echo $value->customerPhone;
	echo '</div><div>Address: ';
	echo $value->customerStreet." ".$value->customerTown.", ".$value->customerState." ".$value->customerZip ;
	echo '</div><div>Role: ';
	echo '<input type="text" class="form-control form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '"></div>';
	echo "<div>";
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo "</div>";
	echo form_close();
	echo "'>";
	echo $count;
	echo '</button>';
	echo '</th><td>';
	echo $value->customerFName;
	echo '</td><td>';
	echo $value->customerLName;
	echo '</td>';
	echo form_open('MGTracker/assignType');
		echo '<input type="hidden" name="customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<td>'; 
	echo $value->CustomerEmail;
	echo '</td><td>';
	echo $value->customerPhone;
	echo '</td><td>';
	echo '<input type="text" class="form-control form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '">';
	echo '</td><td>';
	echo form_submit("submit", "update", "class='submit btn btn-primary btn-sm'");
	echo form_close();
	echo '</td>';
			//customer address and edit
	echo '<td>';
	echo "<button class='btn btn-sm btn-link' id='showAddress' data-toggle='popover' data-placement='left' title='Address' data-html='true' data-content=' ";
	echo '<div>';
	echo form_open('MGTracker/editAddress');
	echo '<input type="hidden" name = "customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>';
	echo form_label('Street', 'customerStreet');
	echo '<input type="text" class="form-control form-control-sm" name="customerStreet" value="';
	echo $value->customerStreet;
	echo '"></div>';
	echo '<div>';
	echo form_label('City', 'customerTown');
	echo '<input type="text" class="form-control form-control-sm" name="customerTown" value="';
	echo $value->customerTown;
	echo '"></div>';
	echo '<div>';
	echo form_label('State', 'customerState');
	echo '<input type="text" class="form-control form-control-sm" name="customerState" value="';
	echo $value->customerState;
	echo '"></div>';
	echo '<div>';
	echo form_label('Zip', 'customerZip');
	echo '<input type="text" class="form-control form-control-sm" name="customerZip" value="';
	echo $value->customerZip;
	echo '"></div>';
	echo '</div>';
	echo form_submit('submit', 'submit', 'class="submit btn btn-primary btn-sm"');
	echo form_close();
	echo "'>";
	echo 'Address</button>';
	echo '</td>';
	echo '</tr>';
	}
	echo '</tbody>';
	echo '</table>';
	echo '</div>';
}elseif($usertype === "employee"){
	echo "<h4>Contacts</h4>";
	//buttons
	echo '<button type="button" id="employeesContact" class="btn btn-primary" data-toggle="collapse" href="#employees" role="button" aria-expanded="false" aria-controls="employees" style="margin-right:2%; margin-bottom:2%;">Co-Workers</button>';
	echo '<button type="button" id="customerContact" class="btn btn-primary" data-toggle="collapse" href="#customers" role="button" aria-expanded="false" aria-controls="customers" style="margin-right:2%; margin-bottom:2%;">Customers</button>';
	//employees
	echo '<div id="employees" class="collapse table-responsive">';
	echo '<h4>Co-Workers</h4>';
	echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th>#</th>';
	echo '<th>First Name</th>';
	echo '<th>Last Name</th>';
	echo '<th>Email</th>';
	echo '<th>Phone Number</th>';
	echo '<th>Role</th>';
	echo '<th>Address</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
	foreach ($employee as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>First Name: ';
	echo $value->customerFName;
	echo '</div><div>Last Name: ';
	echo $value->customerLName;
	echo '</div><div>Email: ';
	echo $value->CustomerEmail;
	echo '</div><div>Phone Number: ';
	echo $value->customerPhone;
	echo '</div><div>Address: ';
	echo $value->customerStreet." ".$value->customerTown.", ".$value->customerState." ".$value->customerZip ;
	echo '</div><div>Role: ';	
	echo $value->usertype;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th><td>';
	echo $value->customerFName;
	echo '</td><td>';
	echo $value->customerLName;
	echo '</td><td>';
	echo $value->CustomerEmail;
	echo '</td><td>';
	echo $value->customerPhone;
	echo '</td><td>';
	echo $value->usertype;
	echo '</td>';
			//customer address and edit
	echo '<td>';
	echo "<button class='btn btn-sm btn-link' id='showAddress' data-toggle='popover' data-placement='left' title='Address' data-html='true' data-content=' ";
	echo '<div>';
	echo form_label('Street', 'customerStreet');
	echo '<input type="text" class="form-control form-control-sm" name="customerStreet" value="';
	echo $value->customerStreet;
	echo '"></div>';
	echo '<div>';
	echo form_label('City', 'customerTown');
	echo '<input type="text" class="form-control form-control-sm" name="customerTown" value="';
	echo $value->customerTown;
	echo '"></div>';
	echo '<div>';
	echo form_label('State', 'customerState');
	echo '<input type="text" class="form-control form-control-sm" name="customerState" value="';
	echo $value->customerState;
	echo '"></div>';
	echo '<div>';
	echo form_label('Zip', 'customerZip');
	echo '<input type="text" class="form-control form-control-sm" name="customerZip" value="';
	echo $value->customerZip;
	echo '"></div>';
	echo '</div>';
	echo "'>";
	echo 'Address</button>';
	echo '</td>';
	echo '</tr>';
	}
	echo '</tbody>';
	echo '</table>';
	echo '</div>';
	//customers
	echo '<div id="customers" class="collapse table-responsive">';
	echo '<div><h4>Customers</h4></div>';
	echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th>#</th>';
	echo '<th>First Name</th>';
	echo '<th>Last Name</th>';
	echo '<th>Email</th>';
	echo '<th>Phone Number</th>';
	echo '<th>Role</th>';
	echo '<th>Address</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
	foreach ($customers as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo '<button class="btn btn-sm btn-link" id="showdetails" data-toggle="popover" data-placement="left" data-trigger="focus" title="Details" data-html="true" data-content="';
	echo '<div>First Name: ';
	echo $value->customerFName;
	echo '</div><div>Last Name: ';
	echo $value->customerLName;
	echo '</div><div>Email: ';
	echo $value->CustomerEmail;
	echo '</div><div>Phone Number: ';
	echo $value->customerPhone;
	echo '</div><div>Address: ';
	echo $value->customerStreet." ".$value->customerTown.", ".$value->customerState." ".$value->customerZip ;
	echo '</div><div>Role: ';
	echo $value->usertype;
	echo '</div>';
	echo '">';
	echo $count;
	echo '</button>';
	echo '</th><td>';
	echo $value->customerFName;
	echo '</td><td>';
	echo $value->customerLName;
	echo '</td><td>';
	echo $value->CustomerEmail;
	echo '</td><td>';
	echo $value->customerPhone;
	echo '</td><td>';
	echo $value->usertype;
	echo '</td>';
	//customer address and edit
	echo '<td>';
	echo "<button class='btn btn-sm btn-link' id='showAddress' data-toggle='popover' data-placement='left' title='Address' data-html='true' data-content=' ";
	echo '<div>';
	echo form_open('MGTracker/editAddress');
	echo '<input type="hidden" name = "customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>';
	echo form_label('Street', 'customerStreet');
	echo '<input type="text" class="form-control form-control-sm" name="customerStreet" value="';
	echo $value->customerStreet;
	echo '"></div>';
	echo '<div>';
	echo form_label('City', 'customerTown');
	echo '<input type="text" class="form-control form-control-sm" name="customerTown" value="';
	echo $value->customerTown;
	echo '"></div>';
	echo '<div>';
	echo form_label('State', 'customerState');
	echo '<input type="text" class="form-control form-control-sm" name="customerState" value="';
	echo $value->customerState;
	echo '"></div>';
	echo '<div>';
	echo form_label('Zip', 'customerZip');
	echo '<input type="text" class="form-control form-control-sm" name="customerZip" value="';
	echo $value->customerZip;
	echo '"></div>';
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo '</div>';
	echo form_close();
	echo "'>";
	echo 'Address</button>';
	echo '</td>';
	echo '</tr>';
	}
	echo '</tbody>';
	echo '</table>';
	echo '</div>';
}

if($usertype === "superadmin"){
	echo '<h4>Users</h4>';
	echo '<button type="button" id="users" class="btn btn-primary" data-toggle="collapse" href="#users" role="button" aria-expanded="false" aria-controls="users" style="margin-right:2%; margin-bottom:2%;">Customers</button>';
	echo '<div id="users" class="collapse table-responsive">';
	echo '<table class="table table-sm table-striped">';
	echo '<thead>';
	echo '<tr>';
	echo '<th>#</th>';
	echo '<th>user</th>';
	echo '<th>First Name</th>';
	echo '<th>Last Name</th>';
	echo '<th>Email</th>';
	echo '<th>Phone Number</th>';
	echo '<th>Company</th>';
	echo '<th>User Type<th>';
	echo '<th>Address</th>';
	echo '</tr>';
	echo '</thead>';
	echo '<tbody>';
	$count = 0;
	foreach ($allusers as $value) {
	$count = $count + 1;
	echo '<tr>';
	echo '<th scope="row">';
	echo "<button class='btn btn-sm btn-link' id='showdetails' data-toggle='popover' data-placement='left' title='Details' data-html='true' data-content=' ";
	echo form_open('MGTracker/editUsers');
	echo '<input type="hidden" class="form-control form-control-plaintext form-control-sm" name = "customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>Username: ';
	echo '<input type="text" class="form-control form-control-sm" name = "username" value="';
	echo $value->username;
	echo '"></div><div>First Name: ';
	echo '<input type="text" class="form-control form-control-sm" name = "fname" value="';
	echo $value->customerFName;
	echo '"></div><div>Last Name: ';
	echo '<input type="text" class="form-control form-control-sm"  name = "lname" value="';
	echo $value->customerLName;
	echo '"></div><div>Email: ';
	echo '<input type="text" class="form-control form-control-sm" name = "email" value="'; 
	echo $value->CustomerEmail;
	echo '">';
	echo '</div><div>Phone Number: ';
	echo '<input type="text" class="form-control form-control-sm" name = "phone" value="';
	echo $value->customerPhone;
	echo '"></div>';
	echo '<div>Company: ';
	echo '<input type="text" class="form-control form-control-sm" name = "company" value="';
	echo $value->customerCompany;
	echo '"></div><div>User Type: ';
	echo '<input type="text" class="form-control form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '"></div>';
	echo "<div>";
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo "</div>";
	echo form_close();
	echo "'>";
	echo $count;
	echo '</button>';
	echo '</th>';
	echo form_open('MGTracker/editUsers');
	echo '<td>';
	echo '<input type="hidden" class="form-control form-control-plaintext form-control-sm" name = "customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<input type="text" class="form-control form-control-plaintext form-control-sm" name = "username" value="';
	echo $value->username;
	echo '">';
	echo '</td><td>';
	echo '<input type="text" class="form-control form-control-plaintext form-control-sm" name = "fname" value="';
	echo $value->customerFName;
	echo '">';
	echo '</td><td>';
	echo '<input type="text" class="form-control form-control-plaintext form-control-sm"  name = "lname" value="';
	echo $value->customerLName;
	echo '">';
	echo '</td><td>';
	echo '<input type="text" class="form-control form-control-plaintext form-control-sm" name = "email" value="'; 
	echo $value->CustomerEmail;
	echo '">';
	echo '</td><td>';
	echo '<input type="text" class="form-control form-control-plaintext form-control-sm" name = "phone" value="';
	echo $value->customerPhone;
	echo '">';
	echo '</td><td>';
	echo '<input type="text" class="form-control form-control-plaintext form-control-sm" name = "company" value="';
	echo $value->customerCompany;
	echo '">';
	echo '</td><td>';
	echo '<input type="text" class="form-control form-control-plaintext form-control-sm" name="usertype" value="';
	echo $value->usertype;
	echo '">';
	echo '</td><td>';
	echo form_submit("submit", "update", "class='submit btn btn-primary btn-sm'");
	echo form_close();
	echo '</td>';
		//customer address and edit
	echo '<td>';
	echo "<button class='btn btn-sm btn-link' id='showAddress' data-toggle='popover' data-placement='left' title='Address' data-html='true' data-content=' ";
	echo '<div>';
	echo form_open('MGTracker/editAddress');
	echo '<input type="hidden" name = "customerNumber" value="';
	echo $value->customerNumber;
	echo '">';
	echo '<div>';
	echo form_label('Street', 'customerStreet');
	echo '<input type="text" class="form-control form-control-sm" name="customerStreet" value="';
	echo $value->customerStreet;
	echo '"></div>';
	echo '<div>';
	echo form_label('City', 'customerTown');
	echo '<input type="text" class="form-control form-control-sm" name="customerTown" value="';
	echo $value->customerTown;
	echo '"></div>';
	echo '<div>';
	echo form_label('State', 'customerState');
	echo '<input type="text" class="form-control form-control-sm" name="customerState" value="';
	echo $value->customerState;
	echo '"></div>';
	echo '<div>';
	echo form_label('Zip', 'customerZip');
	echo '<input type="text" class="form-control form-control-sm" name="customerZip" value="';
	echo $value->customerZip;
	echo '"></div>';
	echo form_submit('submit', 'update', 'class="submit btn btn-primary btn-sm"');
	echo '</div>';
	echo form_close();
	echo "'>";
	echo 'Address</button>';
	echo '</td>';
	
	echo '</tr>';
	}
	echo '</tbody>';
	echo '</table>';
	echo '</div>';
}

?>